### ISSUE TITLE
Hi~ I have some error when run the script.

### ISSUE THREAD

**Issue by star5o** [fateleak/toutiao-text-classfication-dataset#1]
the error in the follow:
`Traceback (most recent call last):
  File "E:/Python/toutiao-text-classfication-dataset-master/get_data.py", line 123, in <module>
    get_routine()
  File "E:/Python/toutiao-text-classfication-dataset-master/get_data.py", line 110, in get_routine
    ll = fp.readlines()#一次性读全部，但每一行作为一个子句存入一个列表
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence`

What should i do?

**Comment by star5o** [comment]
I find some function, Thinks!
